language: ruby
rvm:
- 2.5.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: 
branches:
  only:
  - master
  - "/pages-(.*)/"
script:
- bundle exec jekyll build

deploy:
  provider: firebase
  token:
    secure: V+7HI4tG8mQLRti+SbpOQQyzWPlqs6XynDHFLh+tKcl/08iyRxVTLg8BwFNYVEZLJatTa+N5vKPUpbg0tqwLlIeIJt0ROvyyIT+HzTt8F1bugfZoKHgSiXOTvbzV1Ap0fdzCnvyLNSoI0m6sTlCR20LSyYiNrAPUlBxRDhBboTJi5d6t1XkjDDR6q2y2RlG416agfi0Mas1LJCr3X1MXVA4gBI7FmiPLFa3e208yDrnTq7WEKdWByzsdix+XVh3vGV8AMBm0q3RWIUgm3cHIsNV/R+/04B5yXmY0yjzihosfzQQPJTf+OLliUCozvu/NZuBR1H1SfokTpQj+pADGq69j3j8cCTIJTmnyP08KKu/sgvHyIRz4RLn6tfxLztvY/J6sGxeEYxVsmTHZm6a8WNCme04tbDqd+SrUVNqLvjTnpaJ54T5wrZ0x6O5LrGS3uoHgy++4UdRB0aW5+aNpBCXYIGZ4d0q3agYUg0O0qhsyKh4vcnD8Wgdxl6/ymhJJKqKPxRkb15if3+zP5Za7EGVodmFn9KqebCtDVXn5dOPmcovEESJOgZQ2hh2dyOjx5M+xi6Hs64aZEhfHxxwIBmZyJmME/zFlz9L1NShZVjcn5fNxiP986jh4g0xWiAwCQjwxlUbOdPIrLnliN4FwRBZq2RKhbLgZgfrnpSCNxBY=